Generalize clonned repo workflow

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,25 +28,43 @@ runs:
   using: 'composite'
 
   steps:
-    - name: Cloning Remote Repositories
+    - name: Env vars for locally clonned repo
+      if: inputs.branch != ''
+      shell: bash -leo pipefail {0}
+      run: |
+        echo "::group::Setting up environment variables for locally clonned repo"
+        export CLONNED_REPO="$HOME/${{ inputs.repo }}"
+        echo "CLONNED_REPO=${CLONNED_REPO}" >> $GITHUB_ENV
+        echo "::endgroup::"
+
+    - name: Cloning remote repository
       if: inputs.branch != ''
       env:
         REPO_URL: "https://github.com/${{ inputs.org }}/${{ inputs.repo }}"
       shell: bash -leo pipefail {0}
       run: |
         echo "::group::Cloning repository"
-        git clone -b ${{ inputs.branch }} "${REPO_URL}" "$HOME/${{ inputs.repo }}"
+        git clone -b ${{ inputs.branch }} "${REPO_URL}" ${CLONNED_REPO}
+        echo "::endgroup::"
+
+    - name: Env vars for externally clonned repo
+      if: inputs.branch == ''
+      shell: bash -leo pipefail {0}
+      run: |
+        echo "::group::Setting up environment variables for externally clonned repo"
+        export CLONNED_REPO="$GITHUB_WORKSPACE"
+        echo "CLONNED_REPO=${CLONNED_REPO}" >> $GITHUB_ENV
         echo "::endgroup::"
 
     - name: Check if LICENSE file exists
       shell: bash -leo pipefail {0}
       run: |
         echo "::group::Checking for LICENSE file"
-        if [ ! -f "$HOME/${{ inputs.repo }}/LICENSE" ]; then
-            echo "LICENSE file not found in $HOME/${{ inputs.repo }}. Exiting..."
+        if [ ! -f "${CLONNED_REPO}/LICENSE" ]; then
+            echo "LICENSE file not found in ${CLONNED_REPO}. Exiting..."
             exit 1
         else
-            cat "$HOME/${{ inputs.repo }}/LICENSE"
+            cat "${CLONNED_REPO}/LICENSE"
         fi
         echo "::endgroup::"
 
@@ -54,7 +72,7 @@ runs:
       shell: bash -leo pipefail {0}
       run: |
         echo "::group::Checking for BNL in LICENSE file"
-        if ! grep -q "Brookhaven National Laboratory" "$HOME/${{ inputs.repo }}/LICENSE"; then
+        if ! grep -q "Brookhaven National Laboratory" "${CLONNED_REPO}/LICENSE"; then
             echo "LICENSE file does not contain 'Brookhaven National Laboratory'. Exiting..."
             exit 1
         fi
@@ -98,7 +116,7 @@ runs:
 
         mkdir -v -p $HOME/.ipython/
         # Copy the entire "startup" directory to the test profile.
-        cp -rv "$HOME/${{ inputs.repo }}" $HOME/.ipython/profile_test
+        cp -rv "${CLONNED_REPO}" $HOME/.ipython/profile_test
         # Remove the top-level .py files as they will be loaded separately from
         # profile_collection/startup dir. That allows proper capturing of the
         # exit code in case IPython startup files have issues.
@@ -346,7 +364,7 @@ runs:
         echo "::group::Activating IPython profile and running tests..."
         conda activate $HOME/env
 
-        cd "$HOME/${{ inputs.repo }}"
+        cd "${CLONNED_REPO}"
 
         # Start Xvfb
         /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
