Check if LICENSE file exists

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -35,6 +35,16 @@ runs:
         git clone -b ${{ inputs.branch }} "${REPO_URL}" "$HOME/${{ inputs.repo }}"
         echo "::endgroup::"
 
+    - name: Check if LICENSE file exists
+      shell: bash -leo pipefail {0}
+      run: |
+        echo "::group::Checking for LICENSE file"
+        if [ ! -f "$HOME/${{ inputs.repo }}/LICENSE" ]; then
+            echo "LICENSE file not found in $HOME/${{ inputs.repo }}. Exiting..."
+            exit 1
+        fi
+        echo "::endgroup::"
+
     - name: Set Up Python
       uses: actions/setup-python@v5
       with:
@@ -144,7 +154,7 @@ runs:
     - name: Cache Conda Environment
       id : cache-conda
       uses: actions/cache@v4
-      with: 
+      with:
         path: ~/download_conda_env
         key: ${{ runner.os }}-${{ env.CONDA_ENV_VERSION }}-${{ inputs.conda_env_md5 }}
 
@@ -315,7 +325,7 @@ runs:
         # Start Xvfb
         /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
         export DISPLAY=:99
-        
+
         command="
         import os
         import glob
